package ee.nikolas.resalepilot.workflow.yaga.shopdiscovery.dto;

import java.util.List;

public record YagaShopDiscoveryResponse(
        String shopSlug,
        String sourceMode,
        int pagesVisited,
        int cardsDiscovered,
        int uniqueCandidates,
        int activePublishedCount,
        int activeNewCount,
        int activeExistingCount,
        int skippedCount,
        int failedCount,
        boolean truncated,
        boolean completenessConfirmed,
        YagaShopDiscoveryStopReason stopReason,
        int initialItemCount,
        Integer declaredTotal,
        String declaredTotalSource,
        boolean declaredTotalTrusted,
        List<Integer> totalsObserved,
        Integer minimumObservedTotal,
        Integer maximumObservedTotal,
        Integer finalObservedTotal,
        boolean totalChangedDuringScan,
        int cumulativeRawCount,
        List<String> paginationInconsistencies,
        List<String> duplicateIdentities,
        List<String> rejectedTotalCandidates,
        List<String> paginationFields,
        Boolean hasNextPage,
        String hasNextSource,
        boolean nextCursorAvailable,
        String nextRequestPath,
        String continuationSource,
        String candidateArraySource,
        List<String> relevantRouteNames,
        boolean trustedShopIdFound,
        List<Integer> offsetsRequested,
        List<Integer> batchSizes,
        List<YagaShopDiscoveredListingResponse> activeNew,
        List<YagaShopDiscoveredListingResponse> activeExisting,
        List<YagaShopDiscoverySkippedResponse> skipped,
        List<YagaShopDiscoveryFailedResponse> failed
) {
}
