CREATE TABLE yaga_accounts
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(120) NOT NULL,
    shop_slug            VARCHAR(150) NOT NULL,
    auth_state_path      VARCHAR(500),
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    auto_refresh_enabled BOOLEAN      NOT NULL DEFAULT TRUE,
    batch_size           INTEGER      NOT NULL DEFAULT 10,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_yaga_accounts_shop_slug
        UNIQUE (shop_slug),
    CONSTRAINT chk_yaga_accounts_batch_size
        CHECK (batch_size >= 1)
);

INSERT INTO yaga_accounts (
    name,
    shop_slug,
    auth_state_path,
    enabled,
    auto_refresh_enabled,
    batch_size
)
VALUES (
    'Default Yaga account',
    'nik-ar',
    '../playwright/.auth/yaga-state.json',
    TRUE,
    TRUE,
    10
);

ALTER TABLE marketplace_listings
    ADD COLUMN yaga_account_id BIGINT;

UPDATE marketplace_listings
SET yaga_account_id = (
    SELECT id
    FROM yaga_accounts
    WHERE shop_slug = 'nik-ar'
)
WHERE marketplace = 'YAGA';

ALTER TABLE marketplace_listings
    ALTER COLUMN yaga_account_id SET NOT NULL;

ALTER TABLE marketplace_listings
    ADD CONSTRAINT fk_marketplace_listings_yaga_account
        FOREIGN KEY (yaga_account_id)
            REFERENCES yaga_accounts (id)
            ON DELETE RESTRICT;

CREATE INDEX idx_marketplace_listings_yaga_account
    ON marketplace_listings (yaga_account_id);

ALTER TABLE yaga_refresh_runs
    ADD COLUMN yaga_account_id BIGINT;

UPDATE yaga_refresh_runs
SET yaga_account_id = (
    SELECT id
    FROM yaga_accounts
    WHERE shop_slug = 'nik-ar'
);

ALTER TABLE yaga_refresh_runs
    ALTER COLUMN yaga_account_id SET NOT NULL;

ALTER TABLE yaga_refresh_runs
    ADD CONSTRAINT fk_yaga_refresh_runs_account
        FOREIGN KEY (yaga_account_id)
            REFERENCES yaga_accounts (id)
            ON DELETE RESTRICT;

CREATE INDEX idx_yaga_refresh_runs_account_status_mode
    ON yaga_refresh_runs (yaga_account_id, status, mode);

DROP INDEX uq_yaga_refresh_runs_idempotency_key;

CREATE UNIQUE INDEX uq_yaga_refresh_runs_account_idempotency_key
    ON yaga_refresh_runs (yaga_account_id, trigger_type, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_marketplace_listings_yaga_account_refresh_candidates
    ON marketplace_listings (
        yaga_account_id,
        marketplace,
        status,
        is_current,
        external_created_at,
        created_at,
        id
    );
