CREATE TABLE product_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT       NOT NULL,
    drive_file_id VARCHAR(255) NOT NULL,
    file_name     VARCHAR(255),
    display_order INTEGER      NOT NULL DEFAULT 0,
    is_primary    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_product_images_drive_file
        UNIQUE (product_id, drive_file_id),

    CONSTRAINT chk_product_images_display_order
        CHECK (display_order >= 0)
);

CREATE INDEX idx_product_images_product_id
    ON product_images (product_id);

CREATE UNIQUE INDEX uq_product_images_primary
    ON product_images (product_id)
    WHERE is_primary = TRUE;