CREATE TABLE marketplace_listings
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id              BIGINT       NOT NULL,
    marketplace             VARCHAR(30)  NOT NULL,
    external_listing_id     VARCHAR(100) NOT NULL,
    shop_slug               VARCHAR(150),
    product_slug            VARCHAR(150),
    external_url            TEXT         NOT NULL,
    status                  VARCHAR(30)  NOT NULL,
    external_status         VARCHAR(50),
    external_condition_id   BIGINT,
    external_condition_name VARCHAR(100),
    is_current              BOOLEAN      NOT NULL DEFAULT TRUE,

    external_created_at     TIMESTAMPTZ,
    external_updated_at     TIMESTAMPTZ,
    hidden_at               TIMESTAMPTZ,
    deleted_at              TIMESTAMPTZ,
    last_synced_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    last_error              TEXT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                 BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_marketplace_listings_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_marketplace_external_listing
        UNIQUE (marketplace, external_listing_id),

    CONSTRAINT chk_marketplace_listings_marketplace
        CHECK (marketplace IN ('YAGA')),

    CONSTRAINT chk_marketplace_listings_status
        CHECK (
            status IN (
                       'PUBLISHED',
                       'HIDDEN',
                       'DELETED',
                       'UNKNOWN'
                )
            )
);

CREATE INDEX idx_marketplace_listings_product
    ON marketplace_listings (product_id);

CREATE UNIQUE INDEX uq_marketplace_current_product
    ON marketplace_listings (product_id, marketplace)
    WHERE is_current = TRUE;


CREATE TABLE marketplace_listing_categories
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_listing_id      BIGINT       NOT NULL,
    category_level              INTEGER      NOT NULL,
    external_category_id        BIGINT       NOT NULL,
    parent_external_category_id BIGINT,
    title                       VARCHAR(200) NOT NULL,

    CONSTRAINT fk_listing_categories_listing
        FOREIGN KEY (marketplace_listing_id)
            REFERENCES marketplace_listings (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_listing_category_level
        UNIQUE (
                marketplace_listing_id,
                category_level
            ),

    CONSTRAINT chk_listing_category_level
        CHECK (category_level >= 0)
);

CREATE INDEX idx_listing_categories_listing
    ON marketplace_listing_categories (
                                       marketplace_listing_id
        );


CREATE TABLE marketplace_listing_images
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_listing_id BIGINT       NOT NULL,
    external_image_id      VARCHAR(100) NOT NULL,
    source_url             TEXT         NOT NULL,
    file_name              VARCHAR(255),
    display_order          INTEGER      NOT NULL,

    CONSTRAINT fk_listing_images_listing
        FOREIGN KEY (marketplace_listing_id)
            REFERENCES marketplace_listings (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_listing_external_image
        UNIQUE (
                marketplace_listing_id,
                external_image_id
            ),

    CONSTRAINT chk_listing_image_order
        CHECK (display_order >= 0)
);

CREATE INDEX idx_listing_images_listing
    ON marketplace_listing_images (
                                   marketplace_listing_id
        );